// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package modules

import (
	"context"
)

const getByID = `-- name: GetByID :one
SELECT id, practice_id, name from module WHERE id = $1
`

func (q *Queries) GetByID(ctx context.Context, id int32) (Module, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i Module
	err := row.Scan(&i.ID, &i.PracticeID, &i.Name)
	return i, err
}

const getByNameAndPracticeID = `-- name: GetByNameAndPracticeID :one
SELECT id, practice_id, name from module WHERE practice_id = $1 AND name = $2
`

type GetByNameAndPracticeIDParams struct {
	PracticeID int32
	Name       string
}

func (q *Queries) GetByNameAndPracticeID(ctx context.Context, arg GetByNameAndPracticeIDParams) (Module, error) {
	row := q.db.QueryRow(ctx, getByNameAndPracticeID, arg.PracticeID, arg.Name)
	var i Module
	err := row.Scan(&i.ID, &i.PracticeID, &i.Name)
	return i, err
}

const getByPracticeId = `-- name: GetByPracticeId :many
SELECT id, practice_id, name
FROM module 
WHERE practice_id = $1
ORDER BY id
`

func (q *Queries) GetByPracticeId(ctx context.Context, practiceID int32) ([]Module, error) {
	rows, err := q.db.Query(ctx, getByPracticeId, practiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Module
	for rows.Next() {
		var i Module
		if err := rows.Scan(&i.ID, &i.PracticeID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
