// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package qb_answers

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AiFeedback struct {
	ID        pgtype.UUID      `json:"id"`
	ResultID  int32            `json:"result_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	Header    string           `json:"header"`
	Body      string           `json:"body"`
	Footer    string           `json:"footer"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type AnswerChoice struct {
	ID         int32  `json:"id"`
	QuestionID int32  `json:"question_id"`
	Label      string `json:"label"`
	Text       string `json:"text"`
}

type Module struct {
	ID         int32  `json:"id"`
	PracticeID int32  `json:"practice_id"`
	Name       string `json:"name"`
}

type Practice struct {
	ID        int32            `json:"id"`
	Title     string           `json:"title"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Status    string           `json:"status"`
}

type Question struct {
	ID          int32       `json:"id"`
	Domain      string      `json:"domain"`
	Number      pgtype.Int4 `json:"number"`
	SectionID   int32       `json:"section_id"`
	Paragraph   string      `json:"paragraph"`
	Correct     string      `json:"correct"`
	Svg         pgtype.Text `json:"svg"`
	Prompt      string      `json:"prompt"`
	Explanation string      `json:"explanation"`
	Difficulty  string      `json:"difficulty"`
}

type QuestionBank struct {
	ID          int32       `json:"id"`
	Domain      string      `json:"domain"`
	Paragraph   string      `json:"paragraph"`
	Skill       pgtype.Text `json:"skill"`
	QuestionID  pgtype.Text `json:"question_id"`
	Correct     string      `json:"correct"`
	Prompt      string      `json:"prompt"`
	Explanation string      `json:"explanation"`
	Difficulty  string      `json:"difficulty"`
	AnswerType  pgtype.Text `json:"answer_type"`
	Active      pgtype.Bool `json:"active"`
	ChoiceA     pgtype.Text `json:"choice_a"`
	ChoiceB     pgtype.Text `json:"choice_b"`
	ChoiceC     pgtype.Text `json:"choice_c"`
	ChoiceD     pgtype.Text `json:"choice_d"`
}

type QuestionBankAnswer struct {
	Answer           string             `json:"answer"`
	UserID           pgtype.UUID        `json:"user_id"`
	QuestionID       int32              `json:"question_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Status           string             `json:"status"`
	ResponseDuration pgtype.Int4        `json:"response_duration"`
}

type Result struct {
	ID           int32            `json:"id"`
	UserID       pgtype.UUID      `json:"user_id"`
	PracticeID   int32            `json:"practice_id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	EnglishScore pgtype.Int4      `json:"english_score"`
	MathScore    pgtype.Int4      `json:"math_score"`
	TotalScore   pgtype.Int4      `json:"total_score"`
}

type ResultAnswer struct {
	ID         int32       `json:"id"`
	ResultID   int32       `json:"result_id"`
	QuestionID int32       `json:"question_id"`
	AnswerID   pgtype.Int4 `json:"answer_id"`
	Status     string      `json:"status"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
