// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package qb_answers

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO question_bank_answers (
    answer,
    user_id,
    question_id,
    status,
    response_duration
) VALUES (
    $1,        
    $2,        
    $3,        
    $4,        
    $5         
) RETURNING answer, user_id, question_id, created_at, status, response_duration
`

type CreateParams struct {
	Answer           string      `json:"answer"`
	UserID           pgtype.UUID `json:"user_id"`
	QuestionID       int32       `json:"question_id"`
	Status           string      `json:"status"`
	ResponseDuration pgtype.Int4 `json:"response_duration"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (QuestionBankAnswer, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Answer,
		arg.UserID,
		arg.QuestionID,
		arg.Status,
		arg.ResponseDuration,
	)
	var i QuestionBankAnswer
	err := row.Scan(
		&i.Answer,
		&i.UserID,
		&i.QuestionID,
		&i.CreatedAt,
		&i.Status,
		&i.ResponseDuration,
	)
	return i, err
}

const delete = `-- name: Delete :one
DELETE FROM question_bank_answers WHERE question_id = $1 AND user_id = $2 RETURNING answer, user_id, question_id, created_at, status, response_duration
`

type DeleteParams struct {
	QuestionID int32       `json:"question_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

func (q *Queries) Delete(ctx context.Context, arg DeleteParams) (QuestionBankAnswer, error) {
	row := q.db.QueryRow(ctx, delete, arg.QuestionID, arg.UserID)
	var i QuestionBankAnswer
	err := row.Scan(
		&i.Answer,
		&i.UserID,
		&i.QuestionID,
		&i.CreatedAt,
		&i.Status,
		&i.ResponseDuration,
	)
	return i, err
}

const getByUser = `-- name: GetByUser :many
SELECT answer, user_id, question_id, created_at, status, response_duration FROM question_bank_answers WHERE user_id = $1
`

func (q *Queries) GetByUser(ctx context.Context, userID pgtype.UUID) ([]QuestionBankAnswer, error) {
	rows, err := q.db.Query(ctx, getByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestionBankAnswer
	for rows.Next() {
		var i QuestionBankAnswer
		if err := rows.Scan(
			&i.Answer,
			&i.UserID,
			&i.QuestionID,
			&i.CreatedAt,
			&i.Status,
			&i.ResponseDuration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
