// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package feedbacks

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO ai_feedbacks (
    result_id, 
    user_id, 
    content
) VALUES (
    $1, $2, $3
) 
RETURNING id, result_id, user_id, content, created_at
`

type CreateParams struct {
	ResultID int32
	UserID   pgtype.UUID
	Content  string
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (AiFeedback, error) {
	row := q.db.QueryRow(ctx, create, arg.ResultID, arg.UserID, arg.Content)
	var i AiFeedback
	err := row.Scan(
		&i.ID,
		&i.ResultID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
