// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package feedbacks

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAIFeedback = `-- name: CreateAIFeedback :one
UPDATE test_session SET ai_feedback = $1::JSONB WHERE id = $2 AND user_id = $3 RETURNING id, user_id, practice_id, created_at, ai_feedback, english_score, math_score, total_score
`

type CreateAIFeedbackParams struct {
	Column1 []byte
	ID      int32
	UserID  pgtype.UUID
}

func (q *Queries) CreateAIFeedback(ctx context.Context, arg CreateAIFeedbackParams) (TestSession, error) {
	row := q.db.QueryRow(ctx, createAIFeedback, arg.Column1, arg.ID, arg.UserID)
	var i TestSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PracticeID,
		&i.CreatedAt,
		&i.AiFeedback,
		&i.EnglishScore,
		&i.MathScore,
		&i.TotalScore,
	)
	return i, err
}
