// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package qpractices

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AnswerChoice struct {
	ID         int32
	QuestionID int32
	Label      string
	Text       string
}

type Module struct {
	ID         int32
	PracticeID int32
	Name       string
}

type Practice struct {
	ID        int32
	Title     string
	CreatedAt pgtype.Timestamp
	Status    string
}

type Question struct {
	ID          int32
	Domain      string
	Number      pgtype.Int4
	SectionID   int32
	Paragraph   string
	Correct     string
	Svg         pgtype.Text
	Prompt      string
	Explanation string
	Difficulty  string
}

type TestSession struct {
	ID         int32
	UserID     pgtype.UUID
	PracticeID int32
	CreatedAt  pgtype.Timestamp
}

type TestSessionAnswer struct {
	ID            int32
	UserAnswer    pgtype.Text
	SessionID     int32
	CorrectAnswer string
	Module        string
	Status        string
}
