// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package qpractices

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addQuestion = `-- name: AddQuestion :one
WITH new_question AS (
    INSERT INTO question (domain, number, section_id, paragraph, correct, svg, prompt, explanation, difficulty)
    VALUES (
        $1,  -- domain
        $2,  -- number
        $3,  -- section_id
        $4,  -- paragraph
        $5,  -- correct
        $6,  -- svg (can be NULL)
        $7,  -- prompt
        $8,  -- explanation
        $9   -- difficulty
    )
    RETURNING id
)
INSERT INTO answer_choice (question_id, label, text)
VALUES
    ((SELECT id FROM new_question), $10, $11),
    ((SELECT id FROM new_question), $12, $13),
    ((SELECT id FROM new_question), $14, $15),
    ((SELECT id FROM new_question), $16, $17)
RETURNING id, question_id, label, text
`

type AddQuestionParams struct {
	Domain      string
	Number      pgtype.Int4
	SectionID   int32
	Paragraph   string
	Correct     string
	Svg         pgtype.Text
	Prompt      string
	Explanation string
	Difficulty  string
	Label       string
	Text        string
	Label_2     string
	Text_2      string
	Label_3     string
	Text_3      string
	Label_4     string
	Text_4      string
}

func (q *Queries) AddQuestion(ctx context.Context, arg AddQuestionParams) (AnswerChoice, error) {
	row := q.db.QueryRow(ctx, addQuestion,
		arg.Domain,
		arg.Number,
		arg.SectionID,
		arg.Paragraph,
		arg.Correct,
		arg.Svg,
		arg.Prompt,
		arg.Explanation,
		arg.Difficulty,
		arg.Label,
		arg.Text,
		arg.Label_2,
		arg.Text_2,
		arg.Label_3,
		arg.Text_3,
		arg.Label_4,
		arg.Text_4,
	)
	var i AnswerChoice
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Label,
		&i.Text,
	)
	return i, err
}

const create = `-- name: Create :one
WITH new_practice AS (
    INSERT INTO practice (title)
    VALUES ($1)
    RETURNING id, title, created_at, status
),
inserted_modules AS (
    INSERT INTO module (practice_id, name)
    SELECT id, name
    FROM new_practice, (VALUES 
        ('Reading And Writing 1'),
        ('Reading And Writing 2'),
        ('Math 1'),
        ('Math 2')
    ) AS t(name)
    RETURNING id
)
SELECT id, title, created_at, status FROM new_practice
`

type CreateRow struct {
	ID        int32
	Title     string
	CreatedAt pgtype.Timestamp
	Status    string
}

func (q *Queries) Create(ctx context.Context, title string) (CreateRow, error) {
	row := q.db.QueryRow(ctx, create, title)
	var i CreateRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const createTestSession = `-- name: CreateTestSession :one
INSERT INTO test_session(practice_id, user_id) VALUES($1, $2) RETURNING id, user_id, practice_id, created_at
`

type CreateTestSessionParams struct {
	PracticeID int32
	UserID     pgtype.UUID
}

func (q *Queries) CreateTestSession(ctx context.Context, arg CreateTestSessionParams) (TestSession, error) {
	row := q.db.QueryRow(ctx, createTestSession, arg.PracticeID, arg.UserID)
	var i TestSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PracticeID,
		&i.CreatedAt,
	)
	return i, err
}

const createTestSessionAnswers = `-- name: CreateTestSessionAnswers :many
INSERT INTO test_session_answers (
    user_answer,
    session_id,
    correct_answer,
    module,
    status
) VALUES (
    unnest($1::char(1)[]),
    unnest($2::int[]),
    unnest($3::char(1)[]),
    unnest($4::varchar(50)[]),
    unnest($5::varchar(10)[])
)
RETURNING id, user_answer, session_id, correct_answer, module, status
`

type CreateTestSessionAnswersParams struct {
	UserAnswer    []string
	SessionID     []int32
	CorrectAnswer []string
	Module        []string
	Status        []string
}

func (q *Queries) CreateTestSessionAnswers(ctx context.Context, arg CreateTestSessionAnswersParams) ([]TestSessionAnswer, error) {
	rows, err := q.db.Query(ctx, createTestSessionAnswers,
		arg.UserAnswer,
		arg.SessionID,
		arg.CorrectAnswer,
		arg.Module,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestSessionAnswer
	for rows.Next() {
		var i TestSessionAnswer
		if err := rows.Scan(
			&i.ID,
			&i.UserAnswer,
			&i.SessionID,
			&i.CorrectAnswer,
			&i.Module,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const delete = `-- name: Delete :one
DELETE FROM practice WHERE id = $1 RETURNING id, title, created_at, status
`

func (q *Queries) Delete(ctx context.Context, id int32) (Practice, error) {
	row := q.db.QueryRow(ctx, delete, id)
	var i Practice
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const deleteSessionById = `-- name: DeleteSessionById :one
DELETE FROM test_session WHERE id = $1 AND user_id = $2 RETURNING id, user_id, practice_id, created_at
`

type DeleteSessionByIdParams struct {
	ID     int32
	UserID pgtype.UUID
}

func (q *Queries) DeleteSessionById(ctx context.Context, arg DeleteSessionByIdParams) (TestSession, error) {
	row := q.db.QueryRow(ctx, deleteSessionById, arg.ID, arg.UserID)
	var i TestSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PracticeID,
		&i.CreatedAt,
	)
	return i, err
}

const getAnswerChoicesByQuestionId = `-- name: GetAnswerChoicesByQuestionId :many
SELECT id, label, text, question_id
FROM answer_choice 
WHERE question_id = $1
ORDER BY id
`

type GetAnswerChoicesByQuestionIdRow struct {
	ID         int32
	Label      string
	Text       string
	QuestionID int32
}

func (q *Queries) GetAnswerChoicesByQuestionId(ctx context.Context, questionID int32) ([]GetAnswerChoicesByQuestionIdRow, error) {
	rows, err := q.db.Query(ctx, getAnswerChoicesByQuestionId, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAnswerChoicesByQuestionIdRow
	for rows.Next() {
		var i GetAnswerChoicesByQuestionIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Text,
			&i.QuestionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getById = `-- name: GetById :one
SELECT id, title, created_at
FROM practice 
WHERE id = $1
`

type GetByIdRow struct {
	ID        int32
	Title     string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) GetById(ctx context.Context, id int32) (GetByIdRow, error) {
	row := q.db.QueryRow(ctx, getById, id)
	var i GetByIdRow
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const getExamResultsByUserID = `-- name: GetExamResultsByUserID :many
SELECT 
    ts.id,
    p.title AS practice_title,
    COUNT(CASE WHEN tsa.status = 'correct' THEN 1 END) AS correct_answers,
    COUNT(tsa.id) AS total_questions,
    ts.created_at
FROM test_session ts
JOIN practice p ON ts.practice_id = p.id
LEFT JOIN test_session_answers tsa ON ts.id = tsa.session_id
WHERE ts.user_id = $1
GROUP BY ts.id, p.title, ts.created_at
ORDER BY ts.created_at DESC
`

type GetExamResultsByUserIDRow struct {
	ID             int32
	PracticeTitle  string
	CorrectAnswers int64
	TotalQuestions int64
	CreatedAt      pgtype.Timestamp
}

func (q *Queries) GetExamResultsByUserID(ctx context.Context, userID pgtype.UUID) ([]GetExamResultsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getExamResultsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExamResultsByUserIDRow
	for rows.Next() {
		var i GetExamResultsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PracticeTitle,
			&i.CorrectAnswers,
			&i.TotalQuestions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getModuleID = `-- name: GetModuleID :one
SELECT id from module WHERE practice_id = $1 AND name = $2
`

type GetModuleIDParams struct {
	PracticeID int32
	Name       string
}

func (q *Queries) GetModuleID(ctx context.Context, arg GetModuleIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, getModuleID, arg.PracticeID, arg.Name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getModulesByPracticeId = `-- name: GetModulesByPracticeId :many
SELECT id, name, practice_id
FROM module 
WHERE practice_id = $1
ORDER BY id
`

type GetModulesByPracticeIdRow struct {
	ID         int32
	Name       string
	PracticeID int32
}

func (q *Queries) GetModulesByPracticeId(ctx context.Context, practiceID int32) ([]GetModulesByPracticeIdRow, error) {
	rows, err := q.db.Query(ctx, getModulesByPracticeId, practiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetModulesByPracticeIdRow
	for rows.Next() {
		var i GetModulesByPracticeIdRow
		if err := rows.Scan(&i.ID, &i.Name, &i.PracticeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPracticePreviews = `-- name: GetPracticePreviews :many
SELECT id, title, created_at, status FROM practice
`

func (q *Queries) GetPracticePreviews(ctx context.Context) ([]Practice, error) {
	rows, err := q.db.Query(ctx, getPracticePreviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Practice
	for rows.Next() {
		var i Practice
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionsByModuleId = `-- name: GetQuestionsByModuleId :many
SELECT id, number, domain, difficulty, paragraph, prompt, explanation, correct, section_id
FROM question 
WHERE section_id = $1
ORDER BY number
`

type GetQuestionsByModuleIdRow struct {
	ID          int32
	Number      pgtype.Int4
	Domain      string
	Difficulty  string
	Paragraph   string
	Prompt      string
	Explanation string
	Correct     string
	SectionID   int32
}

func (q *Queries) GetQuestionsByModuleId(ctx context.Context, sectionID int32) ([]GetQuestionsByModuleIdRow, error) {
	rows, err := q.db.Query(ctx, getQuestionsByModuleId, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuestionsByModuleIdRow
	for rows.Next() {
		var i GetQuestionsByModuleIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Domain,
			&i.Difficulty,
			&i.Paragraph,
			&i.Prompt,
			&i.Explanation,
			&i.Correct,
			&i.SectionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionAnswers = `-- name: GetSessionAnswers :many
SELECT id, user_answer, session_id, correct_answer, module, status FROM test_session_answers WHERE session_id = $1 ORDER BY id
`

func (q *Queries) GetSessionAnswers(ctx context.Context, sessionID int32) ([]TestSessionAnswer, error) {
	rows, err := q.db.Query(ctx, getSessionAnswers, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestSessionAnswer
	for rows.Next() {
		var i TestSessionAnswer
		if err := rows.Scan(
			&i.ID,
			&i.UserAnswer,
			&i.SessionID,
			&i.CorrectAnswer,
			&i.Module,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionById = `-- name: GetSessionById :one
SELECT id, user_id, practice_id, created_at FROM test_session WHERE id = $1
`

func (q *Queries) GetSessionById(ctx context.Context, id int32) (TestSession, error) {
	row := q.db.QueryRow(ctx, getSessionById, id)
	var i TestSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PracticeID,
		&i.CreatedAt,
	)
	return i, err
}
