// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package qpractices

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
WITH new_practice AS (
    INSERT INTO practice (title)
    VALUES ($1)
    RETURNING id, title, created_at, status
),
inserted_modules AS (
    INSERT INTO module (practice_id, name)
    SELECT id, name
    FROM new_practice, (VALUES 
        ('Reading And Writing 1'),
        ('Reading And Writing 2'),
        ('Math 1'),
        ('Math 2')
    ) AS t(name)
    RETURNING id
)
SELECT id, title, created_at, status FROM new_practice
`

type CreateRow struct {
	ID        int32
	Title     string
	CreatedAt pgtype.Timestamp
	Status    string
}

func (q *Queries) Create(ctx context.Context, title string) (CreateRow, error) {
	row := q.db.QueryRow(ctx, create, title)
	var i CreateRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const delete = `-- name: Delete :one
DELETE FROM practice WHERE id = $1 RETURNING id, title, created_at, status
`

func (q *Queries) Delete(ctx context.Context, id int32) (Practice, error) {
	row := q.db.QueryRow(ctx, delete, id)
	var i Practice
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getById = `-- name: GetById :one
SELECT id, title, created_at
FROM practice 
WHERE id = $1
`

type GetByIdRow struct {
	ID        int32
	Title     string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) GetById(ctx context.Context, id int32) (GetByIdRow, error) {
	row := q.db.QueryRow(ctx, getById, id)
	var i GetByIdRow
	err := row.Scan(&i.ID, &i.Title, &i.CreatedAt)
	return i, err
}

const getPracticePreviews = `-- name: GetPracticePreviews :many
SELECT id, title, created_at, status FROM practice
`

func (q *Queries) GetPracticePreviews(ctx context.Context) ([]Practice, error) {
	rows, err := q.db.Query(ctx, getPracticePreviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Practice
	for rows.Next() {
		var i Practice
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
