// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package questions

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOpenEnded = `-- name: CreateOpenEnded :one
WITH new_question AS (
    INSERT INTO question (domain, number, section_id, paragraph, correct, svg, prompt, explanation, difficulty)
    VALUES (
        $1,  -- domain
        $2,  -- number
        $3,  -- section_id
        $4,  -- paragraph
        $5,  -- correct
        $6,  -- svg (can be NULL)
        $7,  -- prompt
        $8,  -- explanation
        $9   -- difficulty
    )
    RETURNING id
)
INSERT INTO answer_choice (question_id, label, text)
VALUES
    ((SELECT id FROM new_question), $10, $11)
RETURNING (SELECT id FROM new_question)
`

type CreateOpenEndedParams struct {
	Domain      string
	Number      pgtype.Int4
	SectionID   int32
	Paragraph   string
	Correct     string
	Svg         pgtype.Text
	Prompt      string
	Explanation string
	Difficulty  string
	Label       string
	Text        string
}

func (q *Queries) CreateOpenEnded(ctx context.Context, arg CreateOpenEndedParams) (int32, error) {
	row := q.db.QueryRow(ctx, createOpenEnded,
		arg.Domain,
		arg.Number,
		arg.SectionID,
		arg.Paragraph,
		arg.Correct,
		arg.Svg,
		arg.Prompt,
		arg.Explanation,
		arg.Difficulty,
		arg.Label,
		arg.Text,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createWithAnswerChoices = `-- name: CreateWithAnswerChoices :one
WITH new_question AS (
    INSERT INTO question (domain, number, section_id, paragraph, correct, svg, prompt, explanation, difficulty)
    VALUES (
        $1,  -- domain
        $2,  -- number
        $3,  -- section_id
        $4,  -- paragraph
        $5,  -- correct
        $6,  -- svg (can be NULL)
        $7,  -- prompt
        $8,  -- explanation
        $9   -- difficulty
    )
    RETURNING id
)
INSERT INTO answer_choice (question_id, label, text)
VALUES
    ((SELECT id FROM new_question), $10, $11),
    ((SELECT id FROM new_question), $12, $13),
    ((SELECT id FROM new_question), $14, $15),
    ((SELECT id FROM new_question), $16, $17)
RETURNING id, question_id, label, text
`

type CreateWithAnswerChoicesParams struct {
	Domain      string
	Number      pgtype.Int4
	SectionID   int32
	Paragraph   string
	Correct     string
	Svg         pgtype.Text
	Prompt      string
	Explanation string
	Difficulty  string
	Label       string
	Text        string
	Label_2     string
	Text_2      string
	Label_3     string
	Text_3      string
	Label_4     string
	Text_4      string
}

func (q *Queries) CreateWithAnswerChoices(ctx context.Context, arg CreateWithAnswerChoicesParams) (AnswerChoice, error) {
	row := q.db.QueryRow(ctx, createWithAnswerChoices,
		arg.Domain,
		arg.Number,
		arg.SectionID,
		arg.Paragraph,
		arg.Correct,
		arg.Svg,
		arg.Prompt,
		arg.Explanation,
		arg.Difficulty,
		arg.Label,
		arg.Text,
		arg.Label_2,
		arg.Text_2,
		arg.Label_3,
		arg.Text_3,
		arg.Label_4,
		arg.Text_4,
	)
	var i AnswerChoice
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Label,
		&i.Text,
	)
	return i, err
}

const getByModuleId = `-- name: GetByModuleId :many
SELECT id, number, domain, difficulty, paragraph, prompt, explanation, correct, section_id
FROM question 
WHERE section_id = $1
ORDER BY number
`

type GetByModuleIdRow struct {
	ID          int32
	Number      pgtype.Int4
	Domain      string
	Difficulty  string
	Paragraph   string
	Prompt      string
	Explanation string
	Correct     string
	SectionID   int32
}

func (q *Queries) GetByModuleId(ctx context.Context, sectionID int32) ([]GetByModuleIdRow, error) {
	rows, err := q.db.Query(ctx, getByModuleId, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetByModuleIdRow
	for rows.Next() {
		var i GetByModuleIdRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Domain,
			&i.Difficulty,
			&i.Paragraph,
			&i.Prompt,
			&i.Explanation,
			&i.Correct,
			&i.SectionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByModuleWithChoices = `-- name: GetByModuleWithChoices :many
SELECT
    q.id AS question_id,
    q.number,
    q.domain,
    q.difficulty,
    q.svg,
    q.paragraph,
    q.prompt,
    q.explanation,
    q.correct,
    q.section_id,
    a.id AS answer_id,
    a.label AS answer_label,
    a.text AS answer_text
FROM question q
LEFT JOIN answer_choice a ON a.question_id = q.id
WHERE q.section_id = $1
ORDER BY q.number, a.label
`

type GetByModuleWithChoicesRow struct {
	QuestionID  int32
	Number      pgtype.Int4
	Domain      string
	Difficulty  string
	Svg         pgtype.Text
	Paragraph   string
	Prompt      string
	Explanation string
	Correct     string
	SectionID   int32
	AnswerID    pgtype.Int4
	AnswerLabel pgtype.Text
	AnswerText  pgtype.Text
}

func (q *Queries) GetByModuleWithChoices(ctx context.Context, sectionID int32) ([]GetByModuleWithChoicesRow, error) {
	rows, err := q.db.Query(ctx, getByModuleWithChoices, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetByModuleWithChoicesRow
	for rows.Next() {
		var i GetByModuleWithChoicesRow
		if err := rows.Scan(
			&i.QuestionID,
			&i.Number,
			&i.Domain,
			&i.Difficulty,
			&i.Svg,
			&i.Paragraph,
			&i.Prompt,
			&i.Explanation,
			&i.Correct,
			&i.SectionID,
			&i.AnswerID,
			&i.AnswerLabel,
			&i.AnswerText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
