// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package answer_choices

import (
	"context"
)

const getByQuestionId = `-- name: GetByQuestionId :many
SELECT id, question_id, label, text
FROM answer_choice 
WHERE question_id = $1
ORDER BY id
`

func (q *Queries) GetByQuestionId(ctx context.Context, questionID int32) ([]AnswerChoice, error) {
	rows, err := q.db.Query(ctx, getByQuestionId, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AnswerChoice
	for rows.Next() {
		var i AnswerChoice
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Label,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
