// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package daily_questions

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DailyQuestion struct {
	ID          int32
	Domain      string
	Paragraph   string
	Correct     string
	Svg         pgtype.Text
	Prompt      string
	Explanation string
	Difficulty  string
	CreatedAt   pgtype.Timestamp
	ChoiceA     pgtype.Text
	ChoiceB     pgtype.Text
	ChoiceC     pgtype.Text
	ChoiceD     pgtype.Text
}
