// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package daily_questions

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO daily_question (
    domain,
    paragraph,
    correct,
    svg,
    prompt,
    explanation,
    difficulty,
    choice_a,
    choice_b,
    choice_c,
    choice_d,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, domain, paragraph, correct, svg, prompt, explanation, difficulty, created_at, choice_a, choice_b, choice_c, choice_d
`

type CreateParams struct {
	Domain      string
	Paragraph   string
	Correct     string
	Svg         pgtype.Text
	Prompt      string
	Explanation string
	Difficulty  string
	ChoiceA     pgtype.Text
	ChoiceB     pgtype.Text
	ChoiceC     pgtype.Text
	ChoiceD     pgtype.Text
	CreatedAt   pgtype.Timestamp
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (DailyQuestion, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Domain,
		arg.Paragraph,
		arg.Correct,
		arg.Svg,
		arg.Prompt,
		arg.Explanation,
		arg.Difficulty,
		arg.ChoiceA,
		arg.ChoiceB,
		arg.ChoiceC,
		arg.ChoiceD,
		arg.CreatedAt,
	)
	var i DailyQuestion
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Paragraph,
		&i.Correct,
		&i.Svg,
		&i.Prompt,
		&i.Explanation,
		&i.Difficulty,
		&i.CreatedAt,
		&i.ChoiceA,
		&i.ChoiceB,
		&i.ChoiceC,
		&i.ChoiceD,
	)
	return i, err
}

const getAll = `-- name: GetAll :many
SELECT id, domain, paragraph, correct, svg, prompt, explanation, difficulty, created_at, choice_a, choice_b, choice_c, choice_d FROM daily_question ORDER BY created_at
`

func (q *Queries) GetAll(ctx context.Context) ([]DailyQuestion, error) {
	rows, err := q.db.Query(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyQuestion
	for rows.Next() {
		var i DailyQuestion
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Paragraph,
			&i.Correct,
			&i.Svg,
			&i.Prompt,
			&i.Explanation,
			&i.Difficulty,
			&i.CreatedAt,
			&i.ChoiceA,
			&i.ChoiceB,
			&i.ChoiceC,
			&i.ChoiceD,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatest = `-- name: GetLatest :many
SELECT id, domain, paragraph, correct, svg, prompt, explanation, difficulty, created_at, choice_a, choice_b, choice_c, choice_d
FROM daily_question
WHERE DATE(created_at) = CURRENT_DATE
LIMIT 2
`

func (q *Queries) GetLatest(ctx context.Context) ([]DailyQuestion, error) {
	rows, err := q.db.Query(ctx, getLatest)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailyQuestion
	for rows.Next() {
		var i DailyQuestion
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Paragraph,
			&i.Correct,
			&i.Svg,
			&i.Prompt,
			&i.Explanation,
			&i.Difficulty,
			&i.CreatedAt,
			&i.ChoiceA,
			&i.ChoiceB,
			&i.ChoiceC,
			&i.ChoiceD,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
