    CREATE TABLE IF NOT EXISTS ai_feedbacks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    result_id INT NOT NULL REFERENCES results(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    header TEXT NOT NULL,
    body TEXT NOT NULL,
    footer TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
