// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package question_bank

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AnswerChoice struct {
	ID         int32
	QuestionID int32
	Label      string
	Text       string
}

type DailyQuestion struct {
	ID          int32
	Domain      string
	Paragraph   string
	Correct     string
	Svg         pgtype.Text
	Prompt      string
	Explanation string
	Difficulty  string
	CreatedAt   pgtype.Timestamp
}

type Module struct {
	ID         int32
	PracticeID int32
	Name       string
}

type Practice struct {
	ID        int32
	Title     string
	CreatedAt pgtype.Timestamp
	Status    string
}

type Question struct {
	ID          int32
	Domain      string
	Number      pgtype.Int4
	SectionID   int32
	Paragraph   string
	Correct     string
	Svg         pgtype.Text
	Prompt      string
	Explanation string
	Difficulty  string
}

type QuestionBank struct {
	ID          int32
	Domain      string
	Paragraph   string
	Skill       pgtype.Text
	QuestionID  pgtype.Text
	Correct     string
	Prompt      string
	Explanation string
	Difficulty  string
	AnswerType  pgtype.Text
	Active      pgtype.Bool
	ChoiceA     pgtype.Text
	ChoiceB     pgtype.Text
	ChoiceC     pgtype.Text
	ChoiceD     pgtype.Text
}

type QuestionBankAnswer struct {
	Answer           string
	UserID           pgtype.UUID
	QuestionID       int32
	CreatedAt        pgtype.Timestamptz
	Status           string
	ResponseDuration pgtype.Int4
}

type TestSession struct {
	ID           int32
	UserID       pgtype.UUID
	PracticeID   int32
	CreatedAt    pgtype.Timestamp
	AiFeedback   []byte
	EnglishScore pgtype.Int4
	MathScore    pgtype.Int4
	TotalScore   pgtype.Int4
}

type TestSessionAnswer struct {
	ID            int32
	UserAnswer    pgtype.Text
	SessionID     int32
	CorrectAnswer string
	Module        string
	Status        string
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	FullName     string
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
