// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package question_bank

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO question_bank (
    domain,
    skill,
    paragraph,
    question_id,
    correct,
    prompt,
    explanation,
    difficulty,
    choice_a,
    choice_b,
    choice_c,
    choice_d,
    answer_type,
    active

) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, domain, paragraph, skill, question_id, correct, prompt, explanation, difficulty, answer_type, active, choice_a, choice_b, choice_c, choice_d
`

type CreateParams struct {
	Domain      string
	Skill       pgtype.Text
	Paragraph   string
	QuestionID  pgtype.Text
	Correct     string
	Prompt      string
	Explanation string
	Difficulty  string
	ChoiceA     pgtype.Text
	ChoiceB     pgtype.Text
	ChoiceC     pgtype.Text
	ChoiceD     pgtype.Text
	AnswerType  pgtype.Text
	Active      pgtype.Bool
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (QuestionBank, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Domain,
		arg.Skill,
		arg.Paragraph,
		arg.QuestionID,
		arg.Correct,
		arg.Prompt,
		arg.Explanation,
		arg.Difficulty,
		arg.ChoiceA,
		arg.ChoiceB,
		arg.ChoiceC,
		arg.ChoiceD,
		arg.AnswerType,
		arg.Active,
	)
	var i QuestionBank
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Paragraph,
		&i.Skill,
		&i.QuestionID,
		&i.Correct,
		&i.Prompt,
		&i.Explanation,
		&i.Difficulty,
		&i.AnswerType,
		&i.Active,
		&i.ChoiceA,
		&i.ChoiceB,
		&i.ChoiceC,
		&i.ChoiceD,
	)
	return i, err
}

const getById = `-- name: GetById :one
SELECT question_bank.id, question_bank.domain, question_bank.paragraph, question_bank.skill, question_bank.question_id, question_bank.correct, question_bank.prompt, question_bank.explanation, question_bank.difficulty, question_bank.answer_type, question_bank.active, question_bank.choice_a, question_bank.choice_b, question_bank.choice_c, question_bank.choice_d, question_bank_answers.answer, question_bank_answers.user_id, question_bank_answers.question_id, question_bank_answers.created_at, question_bank_answers.status, question_bank_answers.response_duration 
FROM question_bank 
LEFT JOIN question_bank_answers 
ON question_bank.id = question_bank_answers.question_id AND question_bank_answers.user_id = $1
WHERE question_bank.id = $2
`

type GetByIdParams struct {
	UserID pgtype.UUID
	ID     int32
}

type GetByIdRow struct {
	ID               int32
	Domain           string
	Paragraph        string
	Skill            pgtype.Text
	QuestionID       pgtype.Text
	Correct          string
	Prompt           string
	Explanation      string
	Difficulty       string
	AnswerType       pgtype.Text
	Active           pgtype.Bool
	ChoiceA          pgtype.Text
	ChoiceB          pgtype.Text
	ChoiceC          pgtype.Text
	ChoiceD          pgtype.Text
	Answer           pgtype.Text
	UserID           pgtype.UUID
	QuestionID_2     pgtype.Int4
	CreatedAt        pgtype.Timestamptz
	Status           pgtype.Text
	ResponseDuration pgtype.Int4
}

func (q *Queries) GetById(ctx context.Context, arg GetByIdParams) (GetByIdRow, error) {
	row := q.db.QueryRow(ctx, getById, arg.UserID, arg.ID)
	var i GetByIdRow
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Paragraph,
		&i.Skill,
		&i.QuestionID,
		&i.Correct,
		&i.Prompt,
		&i.Explanation,
		&i.Difficulty,
		&i.AnswerType,
		&i.Active,
		&i.ChoiceA,
		&i.ChoiceB,
		&i.ChoiceC,
		&i.ChoiceD,
		&i.Answer,
		&i.UserID,
		&i.QuestionID_2,
		&i.CreatedAt,
		&i.Status,
		&i.ResponseDuration,
	)
	return i, err
}

const getCollectionDetails = `-- name: GetCollectionDetails :many
SELECT COUNT(id), domain, skill FROM question_bank GROUP BY domain, skill
`

type GetCollectionDetailsRow struct {
	Count  int64
	Domain string
	Skill  pgtype.Text
}

func (q *Queries) GetCollectionDetails(ctx context.Context) ([]GetCollectionDetailsRow, error) {
	rows, err := q.db.Query(ctx, getCollectionDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCollectionDetailsRow
	for rows.Next() {
		var i GetCollectionDetailsRow
		if err := rows.Scan(&i.Count, &i.Domain, &i.Skill); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdBySkill = `-- name: GetIdBySkill :many
SELECT id FROM question_bank WHERE skill = $1
`

func (q *Queries) GetIdBySkill(ctx context.Context, skill pgtype.Text) ([]int32, error) {
	rows, err := q.db.Query(ctx, getIdBySkill, skill)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
